# Configuration du site
title: "NikoStano - 42 Paris"
description: "Documentation des projets de nistanoj @ 42 Paris"
baseurl: ""
url: "https://nikostano.github.io"

# Thème
theme: just-the-docs
color_scheme: dark

# Logo et favicon
logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/favicon.svg"

# Configuration du thème Just the Docs
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Amélioration de la navigation
nav_sort: case_insensitive
nav_external_links:
  - title: GitHub
    url: https://github.com/NikoStano
    hide_icon: false
  - title: 42 Profile
    url: https://profile.intra.42.fr/users/nistanoj
    hide_icon: false

# Retour en haut de page
back_to_top: true
back_to_top_text: "Retour en haut"

# Footer amélioré
footer_content: |
  <div style="text-align: center;">
    <p>© 2024 NikoStano • 42 Paris</p>
    <p style="font-size: 0.875rem; color: #94a3b8;">
      Fait avec ❤️ et beaucoup de ☕
    </p>
  </div>

# Liens de bas de page
gh_edit_link: true
gh_edit_link_text: "✏️ Modifier sur GitHub"
gh_edit_repository: "https://github.com/NikoStano/nikostano.github.io"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"

# Paramètres généraux
permalink: pretty
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - "*.py"
  - migration.md
  - convert_mdx_to_md.py

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-relative-links

# Markdown amélioré
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
    default_lang: plaintext
    css_class: 'highlight'

# Includes custom CSS and JS
head_custom: |
  <link rel="stylesheet" href="{{ '/assets/css/custom.css' | relative_url }}">
  <script defer src="{{ '/assets/js/custom.js' | relative_url }}"></script>
  <!-- Préchargement des polices pour performance -->
  <link rel="preconnect" href="https://fonts.googleapis.com">

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/
  guides:
    output: true
    permalink: /guides/:name/

# Defaults optimisés
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "projects"
      type: "pages"
    values:
      layout: "default"
      parent: "Projets"
  - scope:
      path: "guides"
      type: "pages"
    values:
      layout: "default"
      parent: "Guides"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"
      parent: "Projets"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "default"
      parent: "Guides"

# Compression HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Configuration SEO
author: NikoStano
twitter:
  username: nistanoj
  card: summary_large_image
logo: /assets/images/favicon.svg
social:
  name: NikoStano
  links:
    - https://github.com/NikoStano
    - https://profile.intra.42.fr/users/nistanoj

# Google Analytics (optionnel)
# ga_tracking: UA-XXXXXXXXX-X
# ga_tracking_anonymize_ip: true

# Configuration des couleurs pour le code
# (Compatible avec le dark mode)
code_theme: tomorrow-night